# DAST workflow placeholder
name: DAST - OWASP ZAP Baseline

on:
  workflow_dispatch:
  pull_request:

jobs:
  zap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build API container
        run: |
          docker build -t local-api src/WebApp.Api
          docker run -d -p 5000:80 --name local-api local-api

      - name: Wait for API to be ready
        run: |
          echo "Waiting for API to start..."
          sleep 10
          curl --retry 5 --retry-delay 5 --retry-connrefused http://localhost:5000 || exit 1

      - name: Run ZAP scan
        uses: zaproxy/action-baseline@v0.6.0
        with:
          target: 'http://localhost:5000'
          fail_on_error: true
          format: html

      - name: Upload ZAP report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_report.html